#!/usr/bin/env python3
"""Generate the example golf quote file from English Wikiquote."""

from __future__ import annotations

import argparse
import collections
import html
import json
import re
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


API_URL = "https://en.wikiquote.org/w/api.php"
USER_AGENT = "scorecard-quote-scraper/1.0 (github.com/Lucidedream/scorecard)"
REQUEST_DELAY_SECONDS = 0.55
MIN_QUOTE_LENGTH = 15
MAX_QUOTE_LENGTH = 280
MAX_AUTHOR_LENGTH = 60

THEME_PAGE = "Golf"
GOLFER_PAGES = (
    ("Ben Hogan", ("Ben Hogan", "Ben Hogan (golfer)")),
    ("Jack Nicklaus", ("Jack Nicklaus", "Jack Nicklaus (golfer)")),
    ("Arnold Palmer", ("Arnold Palmer", "Arnold Palmer (golfer)")),
    ("Gary Player", ("Gary Player", "Gary Player (golfer)")),
    ("Lee Trevino", ("Lee Trevino", "Lee Trevino (golfer)")),
    ("Tiger Woods", ("Tiger Woods", "Tiger Woods (golfer)")),
    ("Annika Sörenstam", ("Annika Sörenstam", "Annika Sorenstam", "Annika Sorenstam (golfer)")),
    ("Sam Snead", ("Sam Snead", "Sam Snead (golfer)")),
    ("Bobby Jones", ("Bobby Jones", "Bobby Jones (golfer)")),
    ("Byron Nelson", ("Byron Nelson", "Byron Nelson (golfer)")),
    ("Walter Hagen", ("Walter Hagen", "Walter Hagen (golfer)")),
    ("Seve Ballesteros", ("Seve Ballesteros", "Seve Ballesteros (golfer)")),
    ("Greg Norman", ("Greg Norman", "Greg Norman (golfer)")),
    ("Nick Faldo", ("Nick Faldo", "Nick Faldo (golfer)")),
    ("Phil Mickelson", ("Phil Mickelson", "Phil Mickelson (golfer)")),
    ("Bobby Locke", ("Bobby Locke", "Bobby Locke (golfer)")),
    ("Harvey Penick", ("Harvey Penick", "Harvey Penick (golfer)")),
    ("Tom Watson", ("Tom Watson", "Tom Watson (golfer)")),
    ("Payne Stewart", ("Payne Stewart", "Payne Stewart (golfer)")),
    (
        "Chi-Chi Rodríguez",
        ("Chi-Chi Rodríguez", "Chi-Chi Rodriguez", "Chi-Chi Rodriguez (golfer)"),
    ),
    ("Bernard Darwin", ("Bernard Darwin", "Bernard Darwin (writer)", "Bernard Darwin (golfer)")),
)
GENERAL_FIGURE_PAGES = (
    ("P. G. Wodehouse", ("P. G. Wodehouse",)),
    ("Winston Churchill", ("Winston Churchill",)),
    ("Mark Twain", ("Mark Twain",)),
)

GOLF_KEYWORDS = (
    "golf", "golfer", "golfing", "golfers", "fairway", "putt", "putting", "putter",
    "tee", "teeing", "green", "greens", "bunker", "caddie", "caddy", "birdie",
    "bogey", "par", "links", "clubhouse", "niblick", "mashie", "wedge", "driver",
    "iron", "hole-in-one", "nineteenth hole", "divot", "slice", "hook", "handicap",
)
UNAMBIGUOUS_GOLF_KEYWORDS = (
    "golf", "golfer", "golfing", "golfers", "fairway", "putt", "putter", "teeing",
    "caddie", "caddy", "birdie", "bogey", "clubhouse", "niblick", "mashie",
    "hole-in-one", "nineteenth hole", "divot",
)

OUTPUT_PATH = Path(__file__).resolve().parents[1] / "docs/golf/examples/quotes.txt"
README_PATH = OUTPUT_PATH.with_name("quotes.README.md")

README_TEXT = """# Golf quotes example

`quotes.txt` is generated by `scripts/scrape_golf_quotes.py` from English
Wikiquote. Wikiquote text is available under the
[CC BY-SA 4.0 licence](https://creativecommons.org/licenses/by-sa/4.0/).

Regeneration is a manual development step. To use the generated collection,
copy `quotes.txt` to the SD card as `/golf/quotes.txt`.

Quotes from documented golfers are collected from their subject pages. Quotes
from the Golf theme page and general figures are retained only when the quote
text contains an explicit golf term; ambiguous terms need additional golf
context on general-figure pages. Bibliography/index-like entries are discarded,
and missing golfer pages are retried with ASCII and golfer-title variants where
appropriate.
"""

HEADING_RE = re.compile(r"^(={2,6})\s*(.*?)\s*\1\s*$")
TOP_LEVEL_RE = re.compile(r"^\*\s+(.*)$")
NESTED_RE = re.compile(r"^\*\*+\s+(.*)$")
COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
REF_RE = re.compile(r"<ref\b[^>]*>.*?</ref\s*>|<ref\b[^>]*/\s*>", re.I | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
WIKILINK_RE = re.compile(r"\[\[(?:[^\]|]*\|)?([^\]]+)\]\]")
EXTERNAL_LINK_RE = re.compile(r"\[https?://[^\s\]]+(?:\s+([^\]]+))?\]")
DIALOGUE_BREAK_RE = re.compile(r'"\s*<br\s*/?>\s*--\s*"', re.I)
BOLD_AUTHOR_RE = re.compile(r"'''\s*(.+?)\s*'''")
AUTHOR_LABEL_RE = re.compile(r"\bAuthor\s*:\s*(.+)", re.I)
TRAILING_PAGE_RANGE_RE = re.compile(
    r",\s*\d+\s*[-–]\s*\d+(?:;?\s*(?:\.{3}|…))?\s*$"
)
GOLF_KEYWORD_RE = re.compile(
    r"(?<!\w)(?:" + "|".join(re.escape(word) for word in GOLF_KEYWORDS) + r")(?!\w)",
    re.I,
)
UNAMBIGUOUS_GOLF_KEYWORD_RE = re.compile(
    r"(?<!\w)(?:"
    + "|".join(re.escape(word) for word in UNAMBIGUOUS_GOLF_KEYWORDS)
    + r")(?!\w)",
    re.I,
)

SKIPPED_SECTIONS = {
    "see also",
    "external links",
    "references",
    "further reading",
    "bibliography",
    "notes",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help=f"output path (default: {OUTPUT_PATH})",
    )
    return parser.parse_args()


def fetch_wikitext(page: str) -> str | None:
    query = urllib.parse.urlencode(
        {
            "action": "parse",
            "format": "json",
            "formatversion": "2",
            "prop": "wikitext",
            "redirects": "1",
            "page": page,
        }
    )
    request = urllib.request.Request(
        f"{API_URL}?{query}",
        headers={"User-Agent": USER_AGENT, "Accept": "application/json"},
    )

    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                payload = json.load(response)
            if "error" in payload:
                error = payload["error"]
                print(
                    f"warning: {page}: {error.get('code', 'API error')}: "
                    f"{error.get('info', 'no details')}",
                    file=sys.stderr,
                )
                return None
            return payload["parse"]["wikitext"]
        except urllib.error.HTTPError as error:
            if error.code != 429 or attempt == 3:
                print(f"warning: {page}: HTTP {error.code}", file=sys.stderr)
                return None
            retry_after = error.headers.get("Retry-After")
            delay = float(retry_after) if retry_after and retry_after.isdigit() else 2 ** (attempt + 1)
            time.sleep(delay)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, KeyError) as error:
            print(f"warning: {page}: {error}", file=sys.stderr)
            return None
    return None


def replace_templates(text: str) -> str:
    """Remove templates, retaining the visible name from simple link templates."""

    template_re = re.compile(r"\{\{([^{}]*)\}\}")
    while True:
        match = template_re.search(text)
        if not match:
            return text
        fields = [field.strip() for field in match.group(1).split("|")]
        replacement = ""
        if fields and fields[0].casefold() in {"w", "wikipedia", "author"} and len(fields) > 1:
            visible_fields = [field for field in fields[1:] if "=" not in field]
            if visible_fields:
                replacement = visible_fields[-1]
        text = text[: match.start()] + replacement + text[match.end() :]


def strip_markup(text: str) -> str:
    text = COMMENT_RE.sub(" ", text)
    text = REF_RE.sub(" ", text)
    text = DIALOGUE_BREAK_RE.sub(" ", text)
    text = re.sub(r"<br\s*/?>", " ", text, flags=re.I)
    text = replace_templates(text)
    text = WIKILINK_RE.sub(r"\1", text)
    text = EXTERNAL_LINK_RE.sub(lambda match: match.group(1) or "", text)
    text = TAG_RE.sub(" ", text)
    text = text.replace("'''", "").replace("''", "")
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def strip_surrounding_quotes(text: str) -> str:
    pairs = {'"': '"', "'": "'", "“": "”", "‘": "’"}
    text = text.strip()
    while len(text) >= 2 and text[0] in pairs and text[-1] == pairs[text[0]]:
        text = text[1:-1].strip()
    return text


def typographic_quotes(text: str) -> str:
    output: list[str] = []
    opening = True
    for char in text:
        if char == '"':
            output.append("“" if opening else "”")
            opening = not opening
        elif char == "'":
            output.append("’")
        else:
            output.append(char)
    return "".join(output)


def clean_text(text: str) -> str:
    return typographic_quotes(strip_surrounding_quotes(strip_markup(text)))


def plausible_author(author: str) -> str | None:
    author = clean_text(author)
    author = re.split(
        r"\s+(?:as quoted|in an interview|quoted in)\b", author, maxsplit=1, flags=re.I
    )[0]
    author = author.strip(" ,.;:–—-")
    if not author or len(author) > MAX_AUTHOR_LENGTH or not any(char.isalpha() for char in author):
        return None
    rejected = ("as quoted", "quoted", "source", "variant", "translation", "isbn")
    if author.casefold().startswith(rejected):
        return None
    return author


def author_from_metadata(lines: list[str]) -> str | None:
    for raw_line in lines:
        match = BOLD_AUTHOR_RE.search(raw_line)
        if match:
            author = plausible_author(match.group(1))
            if author:
                return author

        cleaned = strip_markup(raw_line)
        match = AUTHOR_LABEL_RE.search(cleaned)
        if match:
            author = plausible_author(re.split(r"[,;]", match.group(1), maxsplit=1)[0])
            if author:
                return author

        # Wikiquote citation lists normally begin with the speaker's name.
        prefix = re.split(r"\s*,\s*|\s+[—–]\s+", cleaned, maxsplit=1)[0]
        author = plausible_author(prefix)
        if author and len(author.split()) <= 6:
            return author
    return None


def bibliography_like(quote: str) -> bool:
    trimmed = quote.strip(" \t\r\n.,;:!?\"'“”‘’()[]{}—–-")
    return (
        len(trimmed) < MIN_QUOTE_LENGTH
        or quote.count(";") >= 3
        or TRAILING_PAGE_RANGE_RE.search(quote) is not None
    )


def golf_relevant(quote: str, require_unambiguous_keyword: bool) -> bool:
    if GOLF_KEYWORD_RE.search(quote) is None:
        return False
    return not require_unambiguous_keyword or UNAMBIGUOUS_GOLF_KEYWORD_RE.search(quote) is not None


def about_section(heading: str) -> bool:
    return heading == "about" or "quotes about" in heading or heading.startswith("about ")


def extract_quotes(
    wikitext: str,
    author_name: str,
    is_theme: bool,
    require_golf_keyword: bool,
    require_unambiguous_keyword: bool = False,
) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    section_path: list[str] = []
    raw_quote: str | None = None
    metadata: list[str] = []
    quote_section = True

    def flush() -> None:
        nonlocal raw_quote, metadata
        if raw_quote is None or not quote_section:
            raw_quote = None
            metadata = []
            return

        needs_explicit_author = is_theme
        author = author_from_metadata(metadata) if needs_explicit_author else author_name
        quote = clean_text(raw_quote)
        if author:
            author = plausible_author(author)
        if (
            quote
            and author
            and not bibliography_like(quote)
            and (
                not require_golf_keyword
                or golf_relevant(quote, require_unambiguous_keyword)
            )
        ):
            results.append((quote, author))
        raw_quote = None
        metadata = []

    for line in wikitext.splitlines():
        heading = HEADING_RE.match(line)
        if heading:
            flush()
            level = len(heading.group(1))
            section_path = section_path[: level - 2]
            section_path.append(clean_text(heading.group(2)).casefold())
            quote_section = not any(
                heading in SKIPPED_SECTIONS or "misattributed" in heading
                for heading in section_path
            ) and (is_theme or not any(about_section(heading) for heading in section_path))
            continue

        top_level = TOP_LEVEL_RE.match(line)
        if top_level:
            flush()
            raw_quote = top_level.group(1)
            continue

        nested = NESTED_RE.match(line)
        if nested and raw_quote is not None:
            metadata.append(nested.group(1))

    flush()
    return results


def dedupe_key(quote: str) -> str:
    normalized = unicodedata.normalize("NFKD", quote).casefold()
    return "".join(char for char in normalized if char.isalnum())


def generate() -> tuple[
    list[tuple[str, str]], int, int, dict[str, int], dict[str, tuple[str | None, tuple[str, ...]]]
]:
    extracted: list[tuple[str, str]] = []
    per_page: dict[str, int] = {}
    pages_resolved = 0
    resolutions: dict[str, tuple[str | None, tuple[str, ...]]] = {}
    first_request = True

    sources = (
        (THEME_PAGE, (THEME_PAGE,), True, True, False),
        *((author, titles, False, False, False) for author, titles in GOLFER_PAGES),
        *((author, titles, False, True, True) for author, titles in GENERAL_FIGURE_PAGES),
    )
    for (
        author_name,
        titles,
        is_theme,
        require_golf_keyword,
        require_unambiguous_keyword,
    ) in sources:
        attempted: list[str] = []
        selected_title: str | None = None
        page_quotes: list[tuple[str, str]] = []
        for title in titles:
            if not first_request:
                time.sleep(REQUEST_DELAY_SECONDS)
            first_request = False
            attempted.append(title)
            wikitext = fetch_wikitext(title)
            if wikitext is None:
                continue
            page_quotes = extract_quotes(
                wikitext,
                author_name,
                is_theme,
                require_golf_keyword,
                require_unambiguous_keyword,
            )
            if page_quotes:
                selected_title = title
                pages_resolved += 1
                break
        per_page[author_name] = len(page_quotes)
        resolutions[author_name] = (selected_title, tuple(attempted))
        extracted.extend(page_quotes)

    seen: set[str] = set()
    deduped: list[tuple[str, str]] = []
    for quote, author in extracted:
        if not (MIN_QUOTE_LENGTH <= len(quote) <= MAX_QUOTE_LENGTH):
            continue
        key = dedupe_key(quote)
        if key and key not in seen:
            seen.add(key)
            deduped.append((quote, author))

    final = sorted(deduped, key=lambda item: (item[1].casefold(), item[0].casefold()))
    return final, pages_resolved, len(extracted), per_page, resolutions


def write_outputs(quotes: list[tuple[str, str]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    records = [f"{quote}\n{author}" for quote, author in quotes]
    output_path.write_text("\n\n".join(records) + "\n", encoding="utf-8", newline="\n")
    readme_path = output_path.with_name(README_PATH.name)
    readme_path.write_text(README_TEXT, encoding="utf-8", newline="\n")


def main() -> int:
    args = parse_args()
    quotes, pages_resolved, raw_count, per_page, resolutions = generate()
    write_outputs(quotes, args.output)

    author_counts = collections.Counter(author for _, author in quotes)
    page_count = 1 + len(GOLFER_PAGES) + len(GENERAL_FIGURE_PAGES)
    print(f"pages resolved: {pages_resolved}/{page_count}", file=sys.stderr)
    print(f"raw count: {raw_count}", file=sys.stderr)
    print(f"after-dedupe count: {len(quotes)}", file=sys.stderr)
    print(f"final count: {len(quotes)}", file=sys.stderr)
    print("authors:", file=sys.stderr)
    for author, count in sorted(author_counts.items(), key=lambda item: item[0].casefold()):
        print(f"  {author}: {count}", file=sys.stderr)
    print("page results:", file=sys.stderr)
    for page, (selected_title, attempted) in resolutions.items():
        result = selected_title if selected_title is not None else "none"
        print(
            f"  {page}: {per_page[page]} quote(s); title={result}; "
            f"attempted={', '.join(attempted)}",
            file=sys.stderr,
        )
    little = [f"{page} ({count})" for page, count in per_page.items() if count < 5]
    if little:
        print(f"pages returning fewer than 5 quotes: {', '.join(little)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
