#!/usr/bin/env python3
"""Generate the example golf quote file from cited online collections."""

from __future__ import annotations

import argparse
import collections
import dataclasses
import difflib
import html
import json
import re
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


API_URL = "https://en.wikiquote.org/w/api.php"
USER_AGENT = "scorecard-quote-scraper/2.0 (github.com/Lucidedream/scorecard)"
REQUEST_DELAY_SECONDS = 0.6
MIN_QUOTE_LENGTH = 15
MAX_QUOTE_LENGTH = 110
MAX_AUTHOR_LENGTH = 60

THEME_PAGE = "Golf"
GOLFER_CATEGORIES = (
    "Category:Golfers",
    "Category:World Golf Hall of Fame inductees",
)
GENERAL_FIGURE_PAGES = ("P. G. Wodehouse", "Winston Churchill", "Mark Twain")

GOLF_MONTHLY_URL = "https://www.golfmonthly.com/features/32-best-golf-quotes"
GOLF_MONTHLY_MASTERS_URL = (
    "https://www.golfmonthly.com/tour/us-masters/masters-history-records/"
    "best-masters-quotes-177549"
)
EEE_GOLF_URL = "https://eeegolf.com/funny-golf-quotes/"
SPORTS_FEEL_GOOD_URL = "https://www.sportsfeelgoodstories.com/golf-quotes/"
THE_END_QUOTES_URL = "https://theendquotes.com/best-golf-quotes/"
QUOTLR_URL = "https://quotlr.com/quotes-about-golf/"

OUTPUT_PATH = Path(__file__).resolve().parents[1] / "docs/golf/examples/quotes.txt"
README_PATH = OUTPUT_PATH.with_name("quotes.README.md")

README_TEXT = """# Golf quotes example

`quotes.txt` is generated by `scripts/scrape_golf_quotes.py`. Regeneration is
a manual development step. To use the generated collection, copy `quotes.txt`
to the SD card as `/golf/quotes.txt`.

The collection has two source tiers. Tier 1 contains quotes from English
[Wikiquote's Golf page](https://en.wikiquote.org/wiki/Golf) and subject pages
discovered through the [Golfers](https://en.wikiquote.org/wiki/Category:Golfers)
and [World Golf Hall of Fame inductees](https://en.wikiquote.org/wiki/Category:World_Golf_Hall_of_Fame_inductees)
categories. Wikiquote page text is available under the
[CC BY-SA 4.0 licence](https://creativecommons.org/licenses/by-sa/4.0/). The
generator report names every fetched Wikiquote page and its extraction count.

Tier 2 contains attributed quotes printed by these broader golf-specific
collections:

- [Golf Monthly: 32 Best Golf Quotes](https://www.golfmonthly.com/features/32-best-golf-quotes)
- [Golf Monthly: Best Masters Quotes](https://www.golfmonthly.com/tour/us-masters/masters-history-records/best-masters-quotes-177549)
- [EEE Golf: Funny Golf Quotes](https://eeegolf.com/funny-golf-quotes/)
- [Sports Feel Good Stories: Golf Quotes](https://www.sportsfeelgoodstories.com/golf-quotes/)
- [The End Quotes: Best Golf Quotes](https://theendquotes.com/best-golf-quotes/)
- [Quotlr: Golf Quotes](https://quotlr.com/quotes-about-golf/)

Tier 2 is useful for breadth but has weaker verification than Wikiquote. Its
entries carry a real, non-zero risk of misattribution. The generator rejects
unknown speakers, conflicting attributions, known disputed claims, duplicates,
and quote text longer than 110 characters; it does not fabricate or paraphrase
content. Tier metadata stays in the generator report rather than `quotes.txt`
because the device file format has no metadata field.
"""

GOLF_KEYWORDS = (
    "golf", "golfer", "golfing", "golfers", "fairway", "putt", "putting", "putter",
    "tee", "teeing", "green", "greens", "bunker", "caddie", "caddy", "birdie",
    "bogey", "par", "links", "clubhouse", "niblick", "mashie", "wedge", "driver",
    "iron", "hole-in-one", "nineteenth hole", "divot", "slice", "hook", "handicap",
)
UNAMBIGUOUS_GOLF_KEYWORDS = (
    "golf", "golfer", "golfing", "golfers", "fairway", "putt", "putter", "teeing",
    "caddie", "caddy", "birdie", "bogey", "clubhouse", "niblick", "mashie",
    "hole-in-one", "nineteenth hole", "divot",
)

HEADING_RE = re.compile(r"^(={2,6})\s*(.*?)\s*\1\s*$")
TOP_LEVEL_RE = re.compile(r"^\*\s+(.*)$")
NESTED_RE = re.compile(r"^\*\*+\s+(.*)$")
COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
REF_RE = re.compile(r"<ref\b[^>]*>.*?</ref\s*>|<ref\b[^>]*/\s*>", re.I | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
WIKILINK_RE = re.compile(r"\[\[(?:[^\]|]*\|)?([^\]]+)\]\]")
EXTERNAL_LINK_RE = re.compile(r"\[https?://[^\s\]]+(?:\s+([^\]]+))?\]")
DIALOGUE_BREAK_RE = re.compile(r'"\s*<br\s*/?>\s*--\s*"', re.I)
BOLD_AUTHOR_RE = re.compile(r"'''\s*(.+?)\s*'''")
AUTHOR_LABEL_RE = re.compile(r"\bAuthor\s*:\s*(.+)", re.I)
TRAILING_PAGE_RANGE_RE = re.compile(r",\s*\d+\s*[-–]\s*\d+(?:;?\s*(?:\.{3}|…))?\s*$")
GOLF_KEYWORD_RE = re.compile(
    r"(?<!\w)(?:" + "|".join(re.escape(word) for word in GOLF_KEYWORDS) + r")(?!\w)", re.I
)
UNAMBIGUOUS_GOLF_KEYWORD_RE = re.compile(
    r"(?<!\w)(?:" + "|".join(re.escape(word) for word in UNAMBIGUOUS_GOLF_KEYWORDS) + r")(?!\w)",
    re.I,
)

SKIPPED_SECTIONS = {
    "see also", "external links", "references", "further reading", "bibliography", "notes",
}
REJECTED_AUTHORS = {
    "american proverbs", "anonymous", "author unknown", "sayings", "unknown", "unknown author",
    "various sources",
}
# These are disputed often enough that retaining one listicle's attribution is unsafe.
DISPUTED_QUOTE_FRAGMENTS = (
    "golf is a good walk spoiled",
    "all the other four-letter words were taken",
    "all of the other four-letter words were taken",
    "weapons singularly ill-designed for the purpose",
    "good sportsmanship not to pick up lost",
    "good sportsmanship to not pick up lost",
    "golf and sex are about the only things",
    "sex and golf are the two things",
)


@dataclasses.dataclass(frozen=True)
class Candidate:
    quote: str
    author: str
    tier: str
    source: str


@dataclasses.dataclass
class Report:
    fetched: collections.Counter[str] = dataclasses.field(default_factory=collections.Counter)
    accepted: collections.Counter[str] = dataclasses.field(default_factory=collections.Counter)
    rejected: collections.Counter[str] = dataclasses.field(default_factory=collections.Counter)
    wiki_pages: dict[str, int] = dataclasses.field(default_factory=dict)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    return parser.parse_args()


def fetch_url(url: str) -> str | None:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "text/html,*/*"})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=45) as response:
                return response.read().decode("utf-8", "replace")
        except urllib.error.HTTPError as error:
            if error.code not in {429, 500, 502, 503, 504} or attempt == 3:
                print(f"warning: {url}: HTTP {error.code}", file=sys.stderr)
                return None
            retry_after = error.headers.get("Retry-After")
            delay = float(retry_after) if retry_after and retry_after.isdigit() else 2 ** (attempt + 1)
            time.sleep(delay)
        except (urllib.error.URLError, TimeoutError) as error:
            if attempt == 3:
                print(f"warning: {url}: {error}", file=sys.stderr)
                return None
            time.sleep(2 ** (attempt + 1))
    return None


def fetch_api(params: dict[str, str]) -> dict | None:
    url = f"{API_URL}?{urllib.parse.urlencode(params)}"
    text = fetch_url(url)
    if text is None:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError as error:
        print(f"warning: {url}: {error}", file=sys.stderr)
        return None


def fetch_category_members(category: str, member_type: str = "page") -> list[str]:
    payload = fetch_api(
        {
            "action": "query", "list": "categorymembers", "cmtitle": category,
            "cmlimit": "100", "cmtype": member_type, "format": "json", "formatversion": "2",
        }
    )
    if payload is None:
        return []
    return [member["title"] for member in payload.get("query", {}).get("categorymembers", [])]


def fetch_wikitext(page: str) -> str | None:
    payload = fetch_api(
        {
            "action": "parse", "format": "json", "formatversion": "2",
            "prop": "wikitext", "redirects": "1", "page": page,
        }
    )
    if payload is None:
        return None
    if "error" in payload:
        print(f"warning: {page}: {payload['error'].get('info', 'API error')}", file=sys.stderr)
        return None
    try:
        return payload["parse"]["wikitext"]
    except KeyError:
        print(f"warning: {page}: missing wikitext", file=sys.stderr)
        return None


def replace_templates(text: str) -> str:
    template_re = re.compile(r"\{\{([^{}]*)\}\}")
    while True:
        match = template_re.search(text)
        if not match:
            return text
        fields = [field.strip() for field in match.group(1).split("|")]
        replacement = ""
        if fields and fields[0].casefold() in {"w", "wikipedia", "author"} and len(fields) > 1:
            visible_fields = [field for field in fields[1:] if "=" not in field]
            if visible_fields:
                replacement = visible_fields[-1]
        text = text[: match.start()] + replacement + text[match.end() :]


def strip_markup(text: str) -> str:
    text = COMMENT_RE.sub(" ", text)
    text = REF_RE.sub(" ", text)
    text = DIALOGUE_BREAK_RE.sub(" ", text)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.I)
    text = replace_templates(text)
    text = WIKILINK_RE.sub(r"\1", text)
    text = EXTERNAL_LINK_RE.sub(lambda match: match.group(1) or "", text)
    text = TAG_RE.sub(" ", text)
    text = text.replace("'''", "").replace("''", "")
    return re.sub(r"[ \t\r\f\v]+", " ", html.unescape(text)).strip()


def strip_surrounding_quotes(text: str) -> str:
    pairs = {'"': '"', "'": "'", "“": "”", "‘": "’"}
    text = text.strip()
    while len(text) >= 2 and text[0] in pairs and text[-1] == pairs[text[0]]:
        text = text[1:-1].strip()
    return text.strip('"“”‘’').strip()


def typographic_quotes(text: str) -> str:
    output: list[str] = []
    opening = True
    for char in text:
        if char == '"':
            output.append("“" if opening else "”")
            opening = not opening
        elif char == "'":
            output.append("’")
        else:
            output.append(char)
    return "".join(output)


def clean_text(text: str) -> str:
    text = strip_surrounding_quotes(strip_markup(text))
    text = re.sub(r"\s+--\s+", " — ", text)
    return typographic_quotes(text)


def plausible_author(author: str) -> str | None:
    author = clean_text(author)
    author = re.split(r"\s+(?:as quoted|in an interview|quoted in)\b", author, maxsplit=1, flags=re.I)[0]
    author = author.strip(" ,.;:–—-")
    author = re.split(r"\s+[—–]\s+(?:More|See)\b", author, maxsplit=1)[0].strip()
    author = re.split(r",\s+on\b", author, maxsplit=1, flags=re.I)[0].strip()
    if not author or len(author) > MAX_AUTHOR_LENGTH or not any(char.isalpha() for char in author):
        return None
    if author.casefold() in REJECTED_AUTHORS:
        return None
    if author.casefold().startswith("on "):
        return None
    rejected_prefixes = ("as quoted", "quoted", "source", "variant", "translation", "isbn")
    if author.casefold().startswith(rejected_prefixes):
        return None
    return author


def author_from_metadata(lines: list[str]) -> str | None:
    for raw_line in lines:
        match = BOLD_AUTHOR_RE.search(raw_line)
        if match and (author := plausible_author(match.group(1))):
            return author
        cleaned = strip_markup(raw_line)
        match = AUTHOR_LABEL_RE.search(cleaned)
        if match and (author := plausible_author(re.split(r"[,;]", match.group(1), maxsplit=1)[0])):
            return author
        prefix = re.split(r"\s*,\s*|\s+[—–]\s+", cleaned, maxsplit=1)[0]
        author = plausible_author(prefix)
        if author and len(author.split()) <= 6:
            return author
    return None


def bibliography_like(quote: str) -> bool:
    trimmed = quote.strip(" \t\r\n.,;:!?\"'“”‘’()[]{}—–-")
    return len(trimmed) < MIN_QUOTE_LENGTH or quote.count(";") >= 3 or TRAILING_PAGE_RANGE_RE.search(quote) is not None


def golf_relevant(quote: str, require_unambiguous_keyword: bool) -> bool:
    if GOLF_KEYWORD_RE.search(quote) is None:
        return False
    return not require_unambiguous_keyword or UNAMBIGUOUS_GOLF_KEYWORD_RE.search(quote) is not None


def about_section(heading: str) -> bool:
    return heading == "about" or "quotes about" in heading or heading.startswith("about ")


def extract_wiki_quotes(
    wikitext: str, author_name: str, is_theme: bool, require_golf_keyword: bool,
    require_unambiguous_keyword: bool = False,
) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    section_path: list[str] = []
    raw_quote: str | None = None
    metadata: list[str] = []
    quote_section = True

    def flush() -> None:
        nonlocal raw_quote, metadata
        if raw_quote is None or not quote_section:
            raw_quote = None
            metadata = []
            return
        author = author_from_metadata(metadata) if is_theme else author_name
        quote = clean_text(raw_quote)
        if author and (author := plausible_author(author)) and not bibliography_like(quote):
            if not require_golf_keyword or golf_relevant(quote, require_unambiguous_keyword):
                results.append((quote, author))
        raw_quote = None
        metadata = []

    for line in wikitext.splitlines():
        heading = HEADING_RE.match(line)
        if heading:
            flush()
            level = len(heading.group(1))
            section_path = section_path[: level - 2]
            section_path.append(clean_text(heading.group(2)).casefold())
            quote_section = not any(
                heading in SKIPPED_SECTIONS or "misattributed" in heading for heading in section_path
            ) and (is_theme or not any(about_section(heading) for heading in section_path))
            continue
        if top_level := TOP_LEVEL_RE.match(line):
            flush()
            raw_quote = top_level.group(1)
            continue
        if (nested := NESTED_RE.match(line)) and raw_quote is not None:
            metadata.append(nested.group(1))
    flush()
    return results


def html_elements(page: str, tags: str = "p|li") -> list[str]:
    values: list[str] = []
    for match in re.finditer(rf"<(?:{tags})\b[^>]*>(.*?)</(?:{tags})>", page, re.I | re.S):
        value = strip_markup(match.group(1))
        if value:
            values.append(value)
    return values


def split_printed_pair(text: str) -> tuple[str, str] | None:
    text = text.strip()
    if text[:1] in {'"', "“", "‘"}:
        closing = {'"': '"', "“": "”", "‘": "’"}[text[0]]
        separator = re.search(rf"{re.escape(closing)}\s*[—–-]\s*", text)
        if separator:
            quote = text[1 : separator.start()].strip()
            author = text[separator.end() :].strip()
            if quote and author:
                return quote, author
    if " — " in text:
        quote, author = text.rsplit(" — ", 1)
        return quote.strip(), author.strip()
    return None


def extract_standard_page(page: str) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    for text in html_elements(page):
        if text[:1] in {'"', "“", "‘"} and (pair := split_printed_pair(text)):
            results.append(pair)
    return results


def extract_quotlr_page(page: str) -> list[tuple[str, str]]:
    main = re.search(r"<main\b[^>]*>(.*?)</main>", page, re.I | re.S)
    results: list[tuple[str, str]] = []
    for text in html_elements(main.group(1) if main else page, "p"):
        if " — " in text:
            results.append(tuple(part.strip() for part in text.rsplit(" — ", 1)))
    return [(quote, author) for quote, author in results if golf_relevant(quote, False)]


def extract_numbered_page(page: str) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    for text in html_elements(page, "p"):
        match = re.search(r"(?:^|\n)\d+\.\)\s*(.+?)\n([^\n]+)$", text, re.S)
        if match:
            results.append((match.group(1).strip(), match.group(2).strip()))
    return results


def extract_masters_page(page: str) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    author_pattern = re.compile(r"<p\b[^>]*>\s*<strong>(.*?)</strong>\s*</p>", re.I | re.S)
    paragraph_pattern = re.compile(r"<p\b[^>]*>(.*?)</p>", re.I | re.S)
    for author_match in author_pattern.finditer(page):
        author_text = strip_markup(author_match.group(1))
        author = author_text.split(",", 1)[0].strip()
        quote_match = paragraph_pattern.search(page, author_match.end())
        if quote_match is None:
            continue
        quote_text = strip_markup(quote_match.group(1))
        if quote_text[:1] in {"‘", "“", '"'}:
            closing = {"‘": "’", "“": "”", '"': '"'}[quote_text[0]]
            close_at = quote_text.rfind(closing)
            if close_at > 0:
                results.append((quote_text[1:close_at], author))
    return results


def collect_wiki(report: Report) -> list[Candidate]:
    candidates: list[Candidate] = []
    pages: set[str] = set()
    for category in GOLFER_CATEGORIES:
        pages.update(fetch_category_members(category))
        time.sleep(REQUEST_DELAY_SECONDS)

    golf_subcategories = fetch_category_members("Category:Golf", "subcat")
    print(f"Category:Golf subcategories: {', '.join(golf_subcategories)}", file=sys.stderr)

    sources = [(THEME_PAGE, True, True, False)]
    sources.extend((page, False, False, False) for page in sorted(pages, key=str.casefold))
    sources.extend((page, False, True, True) for page in GENERAL_FIGURE_PAGES)
    for page, is_theme, require_keyword, require_unambiguous in sources:
        time.sleep(REQUEST_DELAY_SECONDS)
        wikitext = fetch_wikitext(page)
        if wikitext is None:
            report.wiki_pages[page] = 0
            continue
        pairs = extract_wiki_quotes(wikitext, page, is_theme, require_keyword, require_unambiguous)
        report.wiki_pages[page] = len(pairs)
        candidates.extend(Candidate(quote, author, "Tier 1", "English Wikiquote") for quote, author in pairs)
    return candidates


def collect_tier_two(report: Report) -> list[Candidate]:
    candidates: list[Candidate] = []
    source_parsers = (
        ("Golf Monthly — 32 Best Golf Quotes", GOLF_MONTHLY_URL, extract_standard_page),
        ("Golf Monthly — Best Masters Quotes", GOLF_MONTHLY_MASTERS_URL, extract_masters_page),
        ("EEE Golf", EEE_GOLF_URL, extract_standard_page),
        ("Sports Feel Good Stories", SPORTS_FEEL_GOOD_URL, extract_numbered_page),
        ("The End Quotes", THE_END_QUOTES_URL, extract_standard_page),
        ("Quotlr", QUOTLR_URL, extract_quotlr_page),
    )
    for source, url, parser in source_parsers:
        page = fetch_url(url)
        if page is None:
            continue
        pairs = parser(page)
        report.fetched[source] += len(pairs)
        candidates.extend(Candidate(quote, author, "Tier 2", source) for quote, author in pairs)
    return candidates


def dedupe_key(quote: str) -> str:
    normalized = unicodedata.normalize("NFKD", quote).casefold()
    return "".join(char for char in normalized if char.isalnum())


def author_key(author: str) -> str:
    return "".join(char for char in unicodedata.normalize("NFKD", author).casefold() if char.isalnum())


def disputed(quote: str) -> bool:
    folded = unicodedata.normalize("NFKD", quote).casefold()
    return any(fragment in folded for fragment in DISPUTED_QUOTE_FRAGMENTS)


def filter_candidates(candidates: list[Candidate], report: Report) -> list[Candidate]:
    cleaned: list[Candidate] = []
    for candidate in candidates:
        quote = clean_text(candidate.quote)
        author = plausible_author(candidate.author)
        if not (MIN_QUOTE_LENGTH <= len(quote) <= MAX_QUOTE_LENGTH):
            report.rejected["length"] += 1
            continue
        if author is None or bibliography_like(quote) or disputed(quote):
            report.rejected["attribution"] += 1
            continue
        cleaned.append(dataclasses.replace(candidate, quote=quote, author=author))

    exact_authors: dict[str, set[str]] = collections.defaultdict(set)
    for candidate in cleaned:
        exact_authors[dedupe_key(candidate.quote)].add(author_key(candidate.author))
    conflicted = {key for key, authors in exact_authors.items() if len(authors) > 1}

    fuzzy_conflicted: set[str] = set()
    unique_by_key = {dedupe_key(candidate.quote): candidate for candidate in cleaned}
    unique_items = list(unique_by_key.items())
    for index, (left_key, left) in enumerate(unique_items):
        if len(left_key) < 35:
            continue
        for right_key, right in unique_items[index + 1 :]:
            if author_key(left.author) == author_key(right.author):
                continue
            shorter, longer = sorted((len(left_key), len(right_key)))
            if shorter / longer < 0.88:
                continue
            if difflib.SequenceMatcher(None, left_key, right_key).ratio() >= 0.94:
                fuzzy_conflicted.update((left_key, right_key))

    seen: set[str] = set()
    final: list[Candidate] = []
    for candidate in cleaned:
        key = dedupe_key(candidate.quote)
        if key in conflicted or key in fuzzy_conflicted:
            report.rejected["attribution"] += 1
            continue
        if not key or key in seen:
            report.rejected["dedup"] += 1
            continue
        near_duplicate = any(
            author_key(candidate.author) == author_key(accepted.author)
            and min(len(key), len(accepted_key)) / max(len(key), len(accepted_key)) >= 0.8
            and difflib.SequenceMatcher(None, key, accepted_key).ratio() >= 0.9
            for accepted_key, accepted in ((dedupe_key(item.quote), item) for item in final)
        )
        if near_duplicate:
            report.rejected["dedup"] += 1
            continue
        seen.add(key)
        final.append(candidate)
        report.accepted[candidate.source] += 1
    return sorted(final, key=lambda item: (item.author.casefold(), item.quote.casefold()))


def generate() -> tuple[list[Candidate], Report]:
    report = Report()
    wiki = collect_wiki(report)
    report.fetched["English Wikiquote"] = len(wiki)
    tier_two = collect_tier_two(report)
    return filter_candidates(wiki + tier_two, report), report


def write_outputs(quotes: list[Candidate], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    records = [f"{candidate.quote}\n{candidate.author}" for candidate in quotes]
    output_path.write_text("\n\n".join(records) + "\n", encoding="utf-8", newline="\n")
    output_path.with_name(README_PATH.name).write_text(README_TEXT, encoding="utf-8", newline="\n")


def print_report(quotes: list[Candidate], report: Report) -> None:
    tier_counts = collections.Counter(candidate.tier for candidate in quotes)
    print(f"final count: {len(quotes)}", file=sys.stderr)
    for tier in ("Tier 1", "Tier 2"):
        print(f"{tier}: {tier_counts[tier]}", file=sys.stderr)
    print("accepted by source:", file=sys.stderr)
    for source in report.fetched:
        print(f"  {source}: {report.accepted[source]} / {report.fetched[source]} candidates", file=sys.stderr)
    print("rejected:", file=sys.stderr)
    for reason in ("length", "dedup", "attribution"):
        print(f"  {reason}: {report.rejected[reason]}", file=sys.stderr)
    print("Wikiquote page extraction:", file=sys.stderr)
    for page, count in report.wiki_pages.items():
        print(f"  {page}: {count}", file=sys.stderr)


def main() -> int:
    args = parse_args()
    quotes, report = generate()
    write_outputs(quotes, args.output)
    print_report(quotes, report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
